# List of 'Magic Words'
# These are the translations to generic field names for a FEMTOOL input file
# All FEMTOOL keywords corresponding to generic keywords should be given
# 
# FEMTOOL      generic
#=========================================================================
[translate]

elements       connectivity
points	       coordinates

[extract]

initialize
timeintegration
userdata
dirichlet
neumann
variables
calculate




